aws_region        = "eu-west-3"
acces-key         = "aws_access_key"
secret-key        = "aws_secret_key"
db_identifier     = "ecf-db"
db_username       = "ecf-admin"
db_password       = "eCf-2025" 
ami_code          = "ami-code"
key_name          = "ecf"