name: Deploy Java App to AWS

on:
  push:
    branches:
      - main  # Déclencher le pipeline sur un push dans main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 📌 Étape 1 : Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 📌 Étape 2 : Installer Java et Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 📌 Étape 3 : Compiler l'application avec Maven
    - name: Build with Maven
      working-directory: HelloWorld
      run: mvn clean package

    # 📌 Étape 4 : Ajouter la clé SSH
    - name: Configure SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ecf.pem
        chmod 600 ecf.pem

    # 📌 Étape 5 : Déployer l'application sur AWS
    - name: Deploy to AWS EC2
      env:
        EC2_IP: ${{ secrets.EC2_IP }}
      run: |
        echo "Transfert du fichier WAR..."
        scp -i ecf.pem -o StrictHostKeyChecking=no target/*.war admin@${EC2_IP}:/home/admin/app.war

        echo "Redémarrage de Tomcat..."
        ssh -i ecf.pem admin@${EC2_IP} << 'EOF'
        sudo systemctl restart tomcat10
        EOF

    # 📌 Étape 6 : Vérifier le déploiement
    - name: Check Deployment
      run: curl -I http://${{ secrets.EC2_IP }}:8080/app
